### ISSUE TITLE
Bookmarking Settings

### ISSUE THREAD

**Issue by robertmaloney** [akalajzi/atom-file-bookmark#1]
Let me start off by commending you for the cool idea. I never really thought about bookmarks until I saw your plugin :smile:.

I tried bookmarking settings just to QA it a bit, and it seems to have crashed the plugin entirely. I would recommend disabling the hotkeys and buttons when looking at that tab.

Also, for those that did this and can't get the plugin to work anymore (because FileBookmarksView is serialized), add `@bookmarks = []` right [here](https://github.com/akalajzi/atom-file-bookmark/blob/master/lib/file-bookmark-view.coffee#L83). Then restart atom, remove that line, and restart again.

**Comment by akalajzi** [comment]
Right, thanks :) I was seriously surprised something similar doesn't already exist.

And yes, I know I didn't handle non-files like settings view yet; its on TODO list. Will try to push the fix as soon as possible. Thanks anyway!

**Comment by akalajzi** [comment]
Should be fixed now.
