### ISSUE TITLE
Add a hotkey for toggling the favorites sidebar

### ISSUE THREAD

**Issue by dkniffin** [akalajzi/atom-file-bookmark#11]
Similar to `cmd-\` to open the tree view. I've set mine up to do `cmd+|`, so it's similar, but that overrides  tree-view:reveal-active-file. Perhaps there's a better shortcut for it?

**Comment by infomaniac50** [comment]
ctrl-cmd-; is not taken and has the additional bonus of sharing the same character as file-bookmark:toggle-bookmark.

You can check the key bindings in real time with `ctrl-.` It will open a panel at the bottom that lists key bindings for the current keyboard code. The first one in the list is the binding that gets run by atom.

**Comment by akalajzi** [comment]
Thanks @infomaniac50 , patch with the shortcut is published.
