### ISSUE TITLE
Increasing font size?

### ISSUE THREAD

**Issue by ArnoBuschmann** [akalajzi/atom-file-bookmark#15]
Hi there and thanks for providing this great Atom package, it is exactly what I have been searchin for :+1: 

Now when using it, one question came up:

The font size for the file names is nicely readable, but I have to look very closely for the folder names as its font size is smaller plus the contrast is lower due to the grey font color. Now I wonder, is there a way to increase the font size?

**Comment by akalajzi** [comment]
Well, you can always style any part of Atom by using its style.less
From main menu, select Atom -> Stylesheet... then paste something like

`span.fb-relative-path.icon.icon-file-directory {
  font-size: 14px !important;
}`

Obviously pick a font size you're comfortable with.

**Comment by akalajzi** [comment]
closing
