### ISSUE TITLE
The hide/show option for the icons is not working on my side with the latest version of atom. 

### ISSUE THREAD

**Issue by darrenjacoby** [akalajzi/atom-file-bookmark#16]
![image](https://cloud.githubusercontent.com/assets/15921694/19929398/d8a909d0-a10b-11e6-850f-c463a90e7d14.png)

**Comment by eksortso** [comment]
This is affecting me as well. I uncheck Icons, and restart Atom. When it opens, no icons, as expected. I switch tabs, and the icons are back, even though Icons is still unchecked.

Atom Version 1.15.0
file-bookmark 1.0.2
