### ISSUE TITLE
Add Toggle Command for Individual Bookmarks

### ISSUE THREAD

**Issue by robertmaloney** [akalajzi/atom-file-bookmark#2]
It would be great if you could make a new command that combined `add` and `remove`.

EDIT: Just saw that the function was already there, but making it a public command would still be nice, like:

```
@subscriptions.add atom.commands.add 'atom-workspace', 'file-bookmark:toggle-bookmark': => @toggleBookmark()
```

**Comment by akalajzi** [comment]
Already done locally, will go out in next patch soon enough.
