### ISSUE TITLE
Bookmark files OUTSIDE of project?

### ISSUE THREAD

**Issue by richcorbs** [akalajzi/atom-file-bookmark#3]
Hello,

This isn't really an issue but a question. Is it possible to bookmark files OUTSIDE of the project?

My use case is to enable quick access from any project to reference/scratch files.

Could I do that with this package? Or do you know of another package that does this?

Thanks,

Rich

**Comment by akalajzi** [comment]
Yes, its possible. You just need to open the file first in the editor (via regular File open option), and you can bookmark it from there and access it whenever. Plugin keeps absolute path to the file.

EDIT: Just to further clarify... Your use case would require that you bookmark those reference files in all projects, as list of bookmarks is saved on per project basis. Having selected bookmarks available in all projects, could be a nice future addition to the package.

**Comment by richcorbs** [comment]
I tried this but the file wasn't in the bookmark list when I went to
another project.

I think this implies the bookmark list is project based. Is that right?

**Comment by akalajzi** [comment]
Yes, exactly. As I sad in previous edit. 
I think having bookmarks 'per project' covers more use cases, but I do understand the need to maybe share some bookmarks across projects. Its an interesting idea; I'll probably implement it in a next minor version (or the one after that).

**Comment by richcorbs** [comment]
Sorry, I responded to the notification email which didn't include your edits.

Thanks for the response. I'll watch for an update! Love how it looks and how easy it is to use.
