### ISSUE TITLE
Improvement: favorite folders

### ISSUE THREAD

**Issue by migmae** [akalajzi/atom-file-bookmark#4]
It would be nice to also mark folders as favorite, especially when we are working with frameworks where we continually move between a few folders

Thanks for the package

**Comment by akalajzi** [comment]
You mean in a way that it adds all files from the folder to favorites?

**Comment by migmae** [comment]
Not, only favorite folder. Clicking on it would be selected in the tree view. It would be as quick access to frequently used folders
